@startuml UNI Capability Model Research
' Source: https://github.com/plantuml-stdlib/Archimate-PlantUML

!includeurl https://raw.githubusercontent.com/plantuml-stdlib/Archimate-PlantUML/master/Archimate.puml
!theme archimate-standard from https://raw.githubusercontent.com/plantuml-stdlib/Archimate-PlantUML/master/themes

title UNI Capability Model (HERMS) - Research

left to right direction

!includesub uni_capability_model.puml!Research

@enduml