@startuml UNI Capability Model Commercial Activity

!include <archimate/Archimate>
!include archimate_custom_processing_and_styling.puml 
' Source: https://github.com/plantuml-stdlib/Archimate-PlantUML

!includesub uni_capability_model.puml!CommercialActivity

@enduml