@startuml UNI Capability Model Enabling Capabilities

!include <archimate/Archimate>
!include archimate_custom_processing_and_styling.puml 
' Source: https://github.com/plantuml-stdlib/Archimate-PlantUML

!includesub uni_capability_model.puml!EnablingCapabilities

@enduml